# Global data split and defaults

data:
  test_size: 0.2
  random_state: 42

# Define experiments. The workflow matrix will reference these keys.
experiments:
  rf_small:
    model: random_forest
    params:
      n_estimators: 50
      max_depth: 3
      random_state: 42
  rf_big:
    model: random_forest
    params:
      n_estimators: 200
      max_depth: null
      random_state: 42
  logreg:
    model: logistic_regression
    params:
      C: 1.0
      max_iter: 1000
      random_state: 42
      n_jobs: null
      solver: lbfgs
      multi_class: auto
